
'use server';

import { db } from '@/lib/firebase';
import type { Resource } from '@/types';
import { 
  collection, 
  getDocs, 
  getDoc, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  doc,
  orderBy, 
  Timestamp,
  serverTimestamp,
  query,
  writeBatch
} from 'firebase/firestore';
import { revalidatePath } from 'next/cache';

export async function getResources(): Promise<Resource[]> {
  if (!db) {
    console.warn("Firestore is not initialized. Returning empty resources array.");
    return [];
  }

  try {
    const resourcesCollection = collection(db, 'resources');
    const q = query(resourcesCollection, orderBy('createdAt', 'desc'));
    const querySnapshot = await getDocs(q);

    // If the database is missing items, perform a full reset and repopulate.
    // This ensures the DB is always in sync with the sample data list.
    if (querySnapshot.docs.length < sampleResources.length) {
      console.log("Resource list is outdated or incomplete, repopulating with full data...");
      const batch = writeBatch(db);
      
      // First, delete all existing documents to prevent duplicates.
      querySnapshot.docs.forEach(existingDoc => {
        batch.delete(existingDoc.ref);
      });

      // Then, add all the new sample resources.
      sampleResources.forEach(resource => {
        const docRef = doc(collection(db, 'resources'));
        const dataWithTimestamp = {
            ...resource,
            createdAt: resource.createdAt ? Timestamp.fromDate(new Date(resource.createdAt)) : serverTimestamp(),
        };
        batch.set(docRef, dataWithTimestamp);
      });
      
      await batch.commit();
      console.log("Full resource list populated successfully.");

      // Re-fetch after populating to return the correct data.
      const newQuerySnapshot = await getDocs(q);
      const resources = newQuerySnapshot.docs.map(doc => {
        const data = doc.data();
        return {
          id: doc.id,
          ...data,
          createdAt: (data.createdAt as Timestamp).toDate(),
        } as Resource;
      });
      return resources;
    }
    
    // If the database is already up-to-date, map and return the existing documents.
    const resources = querySnapshot.docs.map(doc => {
      const data = doc.data();
      return {
        id: doc.id,
        ...data,
        createdAt: (data.createdAt as Timestamp).toDate(),
      } as Resource;
    });

    return resources;
  } catch (error) {
    console.error("Error fetching resources:", error);
    return [];
  }
}

export async function getResourceById(id: string): Promise<Resource | null> {
    if (!db) {
        console.warn("Firestore is not initialized.");
        return null;
    }

    try {
        const resourceRef = doc(db, 'resources', id);
        const docSnap = await getDoc(resourceRef);

        if (!docSnap.exists()) {
            return null;
        }

        const data = docSnap.data();
        return {
            id: docSnap.id,
            ...data,
            createdAt: (data.createdAt as Timestamp).toDate(),
        } as Resource;

    } catch (error) {
        console.error("Error fetching resource by id:", error);
        return null;
    }
}

export async function addResource(resourceData: Omit<Resource, 'id' | 'createdAt'>) {
    if (!db) throw new Error("Firestore is not initialized.");

    const newResource = {
        ...resourceData,
        createdAt: serverTimestamp(),
    };
    
    const resourcesCollection = collection(db, 'resources');
    await addDoc(resourcesCollection, newResource);
    revalidatePath('/resources');
    revalidatePath('/dashboard/resources');
}

export async function updateResource(id: string, resourceData: Partial<Resource>) {
    if (!db) throw new Error("Firestore is not initialized.");
    
    const resourceRef = doc(db, 'resources', id);
    await updateDoc(resourceRef, resourceData);
    revalidatePath('/resources');
    revalidatePath('/dashboard/resources');
}

export async function deleteResource(id: string) {
    if (!db) throw new Error("Firestore is not initialized.");
    
    const resourceRef = doc(db, 'resources', id);
    await deleteDoc(resourceRef);
    revalidatePath('/resources');
    revalidatePath('/dashboard/resources');
}

const sampleResources: Omit<Resource, 'id'>[] = [
  // AI & Machine Learning - Paid
  {
    name: 'OpenAI GPT-4 API',
    description: "Access to the API of OpenAI's most advanced language model for various applications, from text generation to analysis.",
    link: 'https://openai.com/gpt-4/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T10:00:00Z'),
  },
  {
    name: 'Google Cloud AI Platform',
    description: 'A suite of managed ML services that allows you to build, train, and deploy models at scale.',
    link: 'https://cloud.google.com/ai-platform/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:50:00Z'),
  },
  {
    name: 'AWS SageMaker',
    description: 'A fully managed ML service that helps developers and data scientists build, train, and deploy models quickly.',
    link: 'https://aws.amazon.com/sagemaker/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:40:00Z'),
  },
  {
    name: 'Azure Machine Learning',
    description: 'A cloud platform to accelerate the machine learning lifecycle, including training, deployment, and model management.',
    link: 'https://azure.microsoft.com/en-us/products/machine-learning/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:30:00Z'),
  },
  {
    name: 'Hugging Face Hub (Models & Inference APIs)',
    description: 'While it has many free models, it offers paid Inference APIs for production use of popular models.',
    link: 'https://huggingface.co/docs/api-inference/pricing',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:20:00Z'),
  },
  {
    name: 'Cohere API',
    description: 'Offers powerful large language models for generation, embedding, and search, with paid plans for commercial use.',
    link: 'https://cohere.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:10:00Z'),
  },
  {
    name: 'Weights & Biases',
    description: 'A platform for tracking, visualizing, and collaborating on machine learning experiments. Offers paid plans for teams.',
    link: 'https://wandb.ai/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:00:00Z'),
  },
  {
    name: 'RunwayML',
    description: 'A platform for creating visual content using AI (video generation, image editing), with paid plans for advanced features.',
    link: 'https://runwayml.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:50:00Z'),
  },
  {
    name: 'Midjourney',
    description: 'A high-quality text-to-image generator operated via Discord, with subscription plans.',
    link: 'https://www.midjourney.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:40:00Z'),
  },
  {
    name: 'Replicate',
    description: 'Lets you run AI models in the cloud with a simple API, paying only for usage, with many pre-trained models available.',
    link: 'https://replicate.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:30:00Z'),
  },
  // AI & Machine Learning - Free Tier
  {
    name: 'Google Colab',
    description: 'Allows you to write and execute Python code in your browser, with free access to GPUs and TPUs for ML.',
    link: 'https://colab.research.google.com/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:20:00Z'),
  },
  {
    name: 'Kaggle',
    description: 'A data science competition platform that offers free notebooks with GPUs for ML experiments and access to large datasets.',
    link: 'https://www.kaggle.com/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:10:00Z'),
  },
  {
    name: 'TensorFlow Lite',
    description: 'Allows running TensorFlow models on mobile and embedded devices, with free tools and pre-trained models.',
    link: 'https://www.tensorflow.org/lite/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:00:00Z'),
  },
  {
    name: 'PyTorch Mobile',
    description: 'A tool for bringing PyTorch models to mobile devices, with a free framework for development and inference.',
    link: 'https://pytorch.org/mobile/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:50:00Z'),
  },
  {
    name: 'Roboflow',
    description: 'A platform for building computer vision datasets, with a free plan for limited projects and inference.',
    link: 'https://roboflow.com/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:40:00Z'),
  },
  {
    name: 'Hugging Face Hub (Model Repository)',
    description: 'Thousands of pre-trained models and open datasets available for free download and use (API inference can be paid).',
    link: 'https://huggingface.co/models',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:30:00Z'),
  },
  {
    name: 'Google Cloud AI Platform (Free Tier)',
    description: 'Offers credits and free usage limits for some ML services, ideal for experimentation.',
    link: 'https://cloud.google.com/free/docs/gcp-free-tier#ai-ml',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:20:00Z'),
  },
  {
    name: 'AWS Free Tier (SageMaker, Rekognition, etc.)',
    description: 'Several AI/ML services on AWS have a free tier for new users, allowing you to experiment before paying.',
    link: 'https://aws.amazon.com/free/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:10:00Z'),
  },
  {
    name: 'Azure Free Account (Azure ML, Cognitive Services)',
    description: 'Free Azure account with credits and AI/ML services that can be used at no cost for a limited time.',
    link: 'https://azure.microsoft.com/en-us/free/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:00:00Z'),
  },
  {
    name: 'Gradio',
    description: 'A Python library for building quick user interfaces for ML models, allowing for interactive demos for free.',
    link: 'https://www.gradio.app/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:50:00Z'),
  },
  // AI & Machine Learning - Open Source
  {
    name: 'TensorFlow',
    description: 'A complete open-source library for machine learning, developed by Google, widely used for research and production.',
    link: 'https://www.tensorflow.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:40:00Z'),
  },
  {
    name: 'PyTorch',
    description: 'An open-source machine learning framework developed by Facebook (Meta), known for its flexibility and ease of use.',
    link: 'https://pytorch.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:30:00Z'),
  },
  {
    name: 'scikit-learn',
    description: 'A Python library for classic machine learning (classification, regression, clustering), easy to use with excellent documentation.',
    link: 'https://scikit-learn.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:20:00Z'),
  },
  {
    name: 'Keras',
    description: 'A high-level API for building and training deep learning models, which can run on top of TensorFlow or PyTorch.',
    link: 'https://keras.io/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:10:00Z'),
  },
  {
    name: 'Jupyter Notebook / Lab',
    description: 'An open-source interactive computing environment that allows creating and sharing documents containing code, equations, and visualizations.',
    link: 'https://jupyter.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:00:00Z'),
  },
  {
    name: 'MLflow',
    description: 'An open-source platform to manage the ML lifecycle, including experimentation, reproducibility, and deployment.',
    link: 'https://mlflow.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:50:00Z'),
  },
  {
    name: 'OpenMMLab',
    description: 'A collection of open-source tools and benchmarks for computer vision research, including object detection, segmentation, and more.',
    link: 'https://openmmlab.com/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:40:00Z'),
  },
  {
    name: 'FastAI',
    description: 'An open-source library that simplifies training state-of-the-art deep learning models with a high-level API, built on PyTorch.',
    link: 'https://www.fast.ai/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:30:00Z'),
  },
  {
    name: 'Apache MXNet',
    description: 'A scalable and flexible open-source deep learning framework that supports multiple programming languages.',
    link: 'https://mxnet.apache.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:20:00Z'),
  },
  {
    name: 'ONNX (Open Neural Network Exchange)',
    description: 'An open format for representing machine learning models, enabling interoperability between different frameworks.',
    link: 'https://onnx.ai/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:10:00Z'),
  },

  // Developer Tools - Paid
  {
    name: 'JetBrains IntelliJ IDEA Ultimate',
    description: 'A powerful IDE for Java, Kotlin, Scala, and other languages, with advanced features for Spring, databases, etc.',
    link: 'https://www.jetbrains.com/idea/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T10:00:00Z'),
  },
  {
    name: 'Sublime Text',
    description: 'A sophisticated and fast code editor, known for its sleek user interface, high performance, and robust plugins.',
    link: 'https://www.sublimetext.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:50:00Z'),
  },
  {
    name: 'Postman',
    description: 'A collaboration platform for API development, allowing you to design, test, document, and monitor APIs. Offers paid plans for teams.',
    link: 'https://www.postman.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:40:00Z'),
  },
  {
    name: 'TablePlus',
    description: 'A modern native database client for macOS, Windows, and Linux, supporting multiple databases with a clean GUI.',
    link: 'https://tableplus.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:30:00Z'),
  },
  {
    name: 'Fiddler Everywhere',
    description: 'A web debugging proxy that allows you to inspect, debug, and modify HTTP/HTTPS traffic between a computer and the internet.',
    link: 'https://www.telerik.com/fiddler/fiddler-everywhere/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:20:00Z'),
  },
  {
    name: 'DataGrip (JetBrains)',
    description: 'A database IDE that supports multiple DBMSs, providing a unified experience for database development.',
    link: 'https://www.jetbrains.com/datagrip/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:10:00Z'),
  },
  {
    name: 'Tower',
    description: 'A Git GUI client for Mac and Windows that simplifies using Git with an intuitive visual interface.',
    link: 'https://www.git-tower.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:00:00Z'),
  },
  {
    name: 'WebStorm (JetBrains)',
    description: 'A powerful IDE for JavaScript, TypeScript, HTML, and CSS development, ideal for front-end frameworks like React, Angular, and Vue.',
    link: 'https://www.jetbrains.com/webstorm/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:50:00Z'),
  },
  {
    name: 'Beyond Compare',
    description: 'A file and folder comparison tool that allows you to compare and merge text files, folders, zip archives, and FTP sites.',
    link: 'https://www.scootersoftware.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:40:00Z'),
  },
  {
    name: 'Dash',
    description: 'A documentation browser and code snippet manager for developers, with offline access to over 200 API documentation sets.',
    link: 'https://kapeli.com/dash',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:30:00Z'),
  },
  // Developer Tools - Free Tier
  {
    name: 'Postman (Free Tier)',
    description: 'Allows basic use for individuals and small teams, including API collections, testing, and limited documentation.',
    link: 'https://www.postman.com/pricing/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:20:00Z'),
  },
  {
    name: 'GitHub Desktop',
    description: 'An open-source desktop application that simplifies the Git and GitHub workflow, making collaboration easier.',
    link: 'https://desktop.github.com/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:10:00Z'),
  },
  {
    name: 'Insomnia',
    description: 'An open-source REST and GraphQL API client with features for designing, debugging, and testing APIs. Offers robust free functionality.',
    link: 'https://insomnia.rest/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:00:00Z'),
  },
  {
    name: 'DBeaver Community Edition',
    description: 'An open-source universal database client with a GUI for multiple databases.',
    link: 'https://dbeaver.io/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:50:00Z'),
  },
  {
    name: 'Sentry (Free Tier)',
    description: 'Real-time error monitoring that helps discover, triage, and prioritize errors in your production code, with a free plan for small projects.',
    link: 'https://sentry.io/pricing/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'Component',
    createdAt: new Date('2024-05-21T07:40:00Z'),
  },
  {
    name: 'CodeSandbox',
    description: 'An online development environment for web projects, focusing on front-end development and prototyping, offering a free plan.',
    link: 'https://codesandbox.io/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:30:00Z'),
  },
  {
    name: 'Ngrok',
    description: 'Creates secure tunnels to your local machine from the internet, great for testing webhooks or sharing a local development environment, with a free tier.',
    link: 'https://ngrok.com/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:20:00Z'),
  },
  // Developer Tools - Open Source
  {
    name: 'VS Code (Visual Studio Code)',
    description: 'A lightweight yet powerful source-code editor with support for thousands of extensions, making it extremely versatile for any language.',
    link: 'https://code.visualstudio.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:10:00Z'),
  },
  {
    name: 'Git',
    description: 'The most widely used distributed version control system, essential for collaborative development.',
    link: 'https://git-scm.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:00:00Z'),
  },
  {
    name: 'Docker',
    description: 'An open-source platform for developing, shipping, and running applications using containers.',
    link: 'https://www.docker.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-21T06:50:00Z'),
  },
  {
    name: 'Node.js',
    description: 'An open-source JavaScript runtime environment that allows building scalable and high-performance network applications.',
    link: 'https://nodejs.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:40:00Z'),
  },
  {
    name: 'Python',
    description: 'A popular open-source programming language for web development, data science, AI, automation, and more.',
    link: 'https://www.python.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:30:00Z'),
  },
  {
    name: 'Kubernetes',
    description: 'An open-source system for automating the deployment, scaling, and management of containerized applications.',
    link: 'https://kubernetes.io/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-21T06:20:00Z'),
  },
  {
    name: 'ESLint',
    description: 'A linting tool for JavaScript and JSX that helps identify and fix problems in your code.',
    link: 'https://eslint.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:10:00Z'),
  },
  {
    name: 'Prettier',
    description: 'An opinionated code formatter that enforces a consistent style across your entire project, eliminating style discussions.',
    link: 'https://prettier.io/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:00:00Z'),
  },
  {
    name: 'Webpack',
    description: 'An open-source module bundler for JavaScript, which packages assets for use in a browser.',
    link: 'https://webpack.js.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T05:50:00Z'),
  },
  {
    name: 'Vagrant',
    description: 'An open-source tool for building and managing portable and replicable virtual machine environments.',
    link: 'https://www.vagrantup.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T05:40:00Z'),
  },
  
  // DevOps & Hosting - Paid
  {
    name: 'AWS (Amazon Web Services)',
    description: "The world's largest cloud platform, offering a vast range of services for computing, storage, databases, analytics, machine learning, and more.",
    link: 'https://aws.amazon.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T10:00:00Z'),
  },
  {
    name: 'Google Cloud Platform (GCP)',
    description: 'Offers a suite of cloud computing services, including IaaS, PaaS, and serverless environments, with strong integration with ML tools.',
    link: 'https://cloud.google.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:50:00Z'),
  },
  {
    name: 'Microsoft Azure',
    description: 'A cloud computing platform that provides services for development, computing, networking, analytics, storage, and more.',
    link: 'https://azure.microsoft.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:40:00Z'),
  },
  {
    name: 'DigitalOcean',
    description: 'A simple and scalable cloud infrastructure provider, popular among developers for its "Droplets" (VMs) and user-friendly interfaces.',
    link: 'https://www.digitalocean.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:30:00Z'),
  },
  {
    name: 'Vercel',
    description: 'A platform for Static Sites and Serverless Functions, optimized for frameworks like React, Next.js, and Vue, with a focus on high performance and DX.',
    link: 'https://vercel.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:20:00Z'),
  },
  {
    name: 'GitLab CI/CD',
    description: 'An integral part of GitLab, it offers a robust CI/CD solution integrated with code management and other DevOps tools. Paid plans have more features.',
    link: 'https://docs.gitlab.com/ee/ci/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:10:00Z'),
  },
  {
    name: 'Datadog',
    description: 'A monitoring and security platform for large-scale cloud applications, offering infrastructure observability, logs, and APM.',
    link: 'https://www.datadoghq.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:00:00Z'),
  },
  {
    name: 'New Relic',
    description: 'An observability platform that helps understand and optimize the performance of complex software in production.',
    link: 'https://newrelic.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:50:00Z'),
  },
  {
    name: 'HashiCorp Vault',
    description: 'A tool for managing secrets and protecting sensitive data in modern DevOps environments. Offers paid versions with enterprise-level features.',
    link: 'https://www.hashicorp.com/products/vault',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:40:00Z'),
  },
  {
    name: 'JFrog Artifactory',
    description: 'A universal binary repository that manages all software artifacts, with paid plans for larger companies and teams.',
    link: 'https://jfrog.com/artifactory/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:30:00Z'),
  },
  // DevOps & Hosting - Free Tier
  {
    name: 'Netlify',
    description: 'Offers a generous free plan for hosting static sites and SPAs, with CI/CD, HTTPS, and limited serverless functions.',
    link: 'https://www.netlify.com/pricing/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:20:00Z'),
  },
  {
    name: 'Vercel (Hobby Plan)',
    description: 'Allows hosting personal and non-commercial projects for free, with CI/CD and serverless functions.',
    link: 'https://vercel.com/pricing',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:10:00Z'),
  },
  {
    name: 'Render',
    description: 'Offers a free tier for static web services, databases, and more, making it easy to deploy various types of applications.',
    link: 'https://render.com/pricing',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:00:00Z'),
  },
  {
    name: 'Cloudflare Workers',
    description: "Allows you to run JavaScript code on Cloudflare's global network with a generous free plan for daily requests, ideal for the edge.",
    link: 'https://www.cloudflare.com/lp/workers-free/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:50:00Z'),
  },
  {
    name: 'GitHub Actions',
    description: 'The CI/CD service integrated with GitHub offers a significant number of free execution minutes per month for public and private repositories.',
    link: 'https://github.com/features/actions',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:40:00Z'),
  },
  {
    name: 'GitLab CI/CD (Free Tier)',
    description: 'The free version of GitLab (self-managed or GitLab.com) includes full CI/CD functionalities for public and private repositories with minute limits.',
    link: 'https://about.gitlab.com/pricing/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:30:00Z'),
  },
  {
    name: 'Firebase Hosting',
    description: 'Part of Firebase, it offers fast and secure hosting for web content with a generous free plan (Spark Plan).',
    link: 'https://firebase.google.com/docs/hosting/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:20:00Z'),
  },
  {
    name: 'Docker Hub (Free Tier)',
    description: 'A Docker image repository that allows storing and sharing container images, with a free plan for individual use.',
    link: 'https://hub.docker.com/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:10:00Z'),
  },
  {
    name: 'Logtail (Better Stack)',
    description: 'Real-time log monitoring with a free tier that includes a limited volume of logs and retention.',
    link: 'https://betterstack.com/logtail/pricing',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:00:00Z'),
  },
  // DevOps & Hosting - Open Source
  {
    name: 'Jenkins',
    description: 'A leading open-source automation server for CI/CD, flexible and with thousands of plugins.',
    link: 'https://www.jenkins.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:50:00Z'),
  },
  {
    name: 'Ansible',
    description: 'An open-source IT automation tool for configuration management, application deployment, and orchestration.',
    link: 'https://www.ansible.com/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:40:00Z'),
  },
  {
    name: 'Prometheus',
    description: 'An open-source system for real-time monitoring and alerting of systems, popular in cloud-native environments.',
    link: 'https://prometheus.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:30:00Z'),
  },
  {
    name: 'Grafana',
    description: 'An open-source tool for data visualization and analysis, commonly used with Prometheus to create monitoring dashboards.',
    link: 'https://grafana.com/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:20:00Z'),
  },
  {
    name: 'Terraform',
    description: 'An open-source Infrastructure as Code (IaC) tool that allows provisioning and managing infrastructure across various clouds.',
    link: 'https://www.terraform.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:10:00Z'),
  },
  {
    name: 'Nagios',
    description: 'An open-source monitoring system that allows monitoring of systems, networks, and infrastructure.',
    link: 'https://www.nagios.org/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:00:00Z'),
  },
  {
    name: 'ELK Stack (Elasticsearch, Logstash, Kibana)',
    description: 'A set of open-source tools for log and data ingestion, storage, search, and visualization.',
    link: 'https://www.elastic.co/elk-stack/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T05:50:00Z'),
  },
  {
    name: 'Argo CD',
    description: 'A declarative, GitOps-based continuous deployment (CD) tool for Kubernetes.',
    link: 'https://argocd.readthedocs.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T05:40:00Z'),
  },
  
  // Productivity - Paid
  {
    name: 'Notion',
    description: 'An all-in-one workspace for notes, project management, databases, wikis, and collaboration, widely used by developers and teams.',
    link: 'https://www.notion.so/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T10:00:00Z'),
  },
  {
    name: 'Todoist',
    description: 'A to-do list and project management app that helps organize work and personal life, with advanced productivity features.',
    link: 'https://todoist.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:50:00Z'),
  },
  {
    name: 'Forest',
    description: 'A productivity app that helps you focus and avoid distractions by planting a virtual tree while you concentrate.',
    link: 'https://www.forestapp.cc/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:40:00Z'),
  },
  {
    name: 'ClickUp',
    description: 'A project management and productivity platform that centralizes tasks, documents, goals, and chat in one place.',
    link: 'https://clickup.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:30:00Z'),
  },
  {
    name: 'RescueTime',
    description: 'An automatic time-tracking app that monitors your computer activities and provides detailed reports on how you spend your time.',
    link: 'https://www.rescuetime.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:20:00Z'),
  },
  {
    name: 'Things 3 (macOS/iOS)',
    description: 'An award-winning task manager, known for its clean design, intuitive interface, and focus on helping you get things done.',
    link: 'https://culturedcode.com/things/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:10:00Z'),
  },
  {
    name: 'Dashlane',
    description: 'A password manager and digital wallet that helps protect your online accounts and autofill forms, increasing security and productivity.',
    link: 'https://www.dashlane.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:00:00Z'),
  },
  {
    name: 'Krisp',
    description: 'An AI-based noise-canceling app that removes background noise from calls and meetings, improving communication clarity.',
    link: 'https://krisp.ai/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:50:00Z'),
  },
  {
    name: 'Linear',
    description: 'An issue tracker and project management tool focused on high-performance software teams, known for its speed and simplicity.',
    link: 'https://linear.app/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:30:00Z'),
  },
  // Productivity - Free Tier
  {
    name: 'Asana (Basic Plan)',
    description: 'A project and task management tool that allows teams to organize, track, and manage their work. The basic plan is free for smaller teams.',
    link: 'https://asana.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:20:00Z'),
  },
  {
    name: 'Trello',
    description: 'A Kanban-based project management tool, ideal for visual organization of tasks and workflows. Offers a robust free plan.',
    link: 'https://trello.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:10:00Z'),
  },
  {
    name: 'Evernote (Free Plan)',
    description: 'A note-taking app that allows you to capture ideas, organize notes, and manage tasks, with a limited free plan.',
    link: 'https://evernote.com/compare-plans',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:00:00Z'),
  },
  {
    name: 'Slack (Free Plan)',
    description: 'A communication platform for teams, allowing real-time conversations, file sharing, and integration with other tools. The free plan is for basic use.',
    link: 'https://slack.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:50:00Z'),
  },
  {
    name: 'Microsoft To Do',
    description: 'A simple and smart to-do list app that helps plan your day and manage tasks effectively, synced with Outlook. Free with a Microsoft account.',
    link: 'https://todo.microsoft.com/',
    category: 'Productivity',
    pricing: 'Free',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:40:00Z'),
  },
  {
    name: 'Notion (Free Personal Plan)',
    description: 'Free access to basic features for notes, wikis, and project management for individual use.',
    link: 'https://www.notion.so/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:30:00Z'),
  },
  {
    name: 'Google Workspace (Free Apps)',
    description: 'The free versions of Docs, Sheets, Slides, Calendar, Gmail, etc., are essential productivity tools.',
    link: 'https://workspace.google.com/',
    category: 'Productivity',
    pricing: 'Free',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:20:00Z'),
  },
  {
    name: 'Zoom (Basic Plan)',
    description: 'A video conferencing platform that offers free meetings with limited duration and number of participants.',
    link: 'https://zoom.us/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:10:00Z'),
  },
  {
    name: 'Grammarly (Free Version)',
    description: 'A writing tool that checks grammar, spelling, punctuation, and style, helping to improve the clarity of written communication.',
    link: 'https://www.grammarly.com/premium',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:00:00Z'),
  },
  {
    name: 'Calendly (Basic Plan)',
    description: 'A scheduling tool that simplifies booking meetings by allowing others to book times on your available calendar.',
    link: 'https://calendly.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:50:00Z'),
  },
  // Productivity - Open Source
  {
    name: 'Joplin',
    description: 'An open-source note-taking and to-do list app with cloud sync and Markdown support.',
    link: 'https://joplinapp.org/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:40:00Z'),
  },
  {
    name: 'Standard Notes',
    description: 'A simple, private, and open-source note-taking app with a focus on security and encryption.',
    link: 'https://standardnotes.com/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:30:00Z'),
  },
  {
    name: 'Obsidian',
    description: 'A powerful open-source knowledge base software that works on a local directory of Markdown files, ideal for connecting ideas.',
    link: 'https://obsidian.md/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:20:00Z'),
  },
  {
    name: 'Nextcloud',
    description: 'An open-source productivity suite, including file storage, communication, and collaboration tools, that you can host on your own server.',
    link: 'https://nextcloud.com/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:10:00Z'),
  },
  {
    name: 'Mattermost',
    description: 'An open-source collaboration platform alternative to Slack, for teams that need secure and private communication.',
    link: 'https://mattermost.com/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:00:00Z'),
  },
  {
    name: 'Self-hosted GitLab',
    description: 'Besides CI/CD, GitLab (self-hosted version) is a complete DevOps platform that includes project management, wikis, and more, all open source.',
    link: 'https://about.gitlab.com/install/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-19T05:50:00Z'),
  },
  {
    name: 'KanbanFlow',
    description: 'An online Kanban board tool with time tracking and Pomodoro features, with a full-featured free version.',
    link: 'https://kanbanflow.com/',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:40:00Z'),
  },
  {
    name: 'FocusWriter',
    description: 'A simple, distraction-free text editor for writers, designed to help you focus on writing.',
    link: 'https://gottcode.org/focuswriter/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:30:00Z'),
  },
  {
    name: 'OpenProject',
    description: 'An open-source project management software for teams seeking project planning, task management, and time tracking.',
    link: 'https://www.openproject.org/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:20:00Z'),
  },
  {
    name: 'Draw.io (diagrams.net)',
    description: 'A free open-source diagram editor that can be used online or offline to create flowcharts, UML diagrams, and more.',
    link: 'https://app.diagrams.net/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:10:00Z'),
  },

  // Books & Courses - Paid
  {
    name: '"Clean Code" by Robert C. Martin',
    description: 'A classic book that covers the principles of writing clean, maintainable code.',
    link: 'https://www.oreilly.com/library/view/clean-code/9780136083238/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T10:00:00Z'),
  },
  {
    name: '"The Pragmatic Programmer" by David Thomas & Andrew Hunt',
    description: 'Offers practical advice and philosophies on how to become a more effective and productive developer.',
    link: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:50:00Z'),
  },
  {
    name: '"Designing Data-Intensive Applications" by Martin Kleppmann',
    description: 'Essential for software architects and data engineers, covering the principles behind building scalable and resilient data systems.',
    link: 'https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:40:00Z'),
  },
  {
    name: 'Coursera (Specializations/Courses)',
    description: 'An online course platform from renowned universities and companies, with paid specializations and certificates in various tech areas.',
    link: 'https://www.coursera.org/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:30:00Z'),
  },
  {
    name: 'Udemy',
    description: 'A large marketplace of online courses with a vast selection of video tutorials on virtually any technology or programming language, usually with a one-time cost per course.',
    link: 'https://www.udemy.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:20:00Z'),
  },
  {
    name: 'Pluralsight',
    description: 'A technology-focused online learning platform with learning paths, assessments, and courses on software development, cloud, and DevOps.',
    link: 'https://www.pluralsight.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:10:00Z'),
  },
  {
    name: 'Frontend Masters',
    description: 'Offers in-depth courses on front-end development with top-tier instructors, covering JavaScript, React, Vue, Node.js, and more.',
    link: 'https://frontendmasters.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:00:00Z'),
  },
  {
    name: 'Manning Publications (Books & LiveBooks)',
    description: 'A publisher of high-quality technical books on programming, machine learning, and systems, with e-book and online access options.',
    link: 'https://www.manning.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:50:00Z'),
  },
  {
    name: 'Educative.io',
    description: 'An interactive text-based platform for learning programming, with hands-on courses and coding challenges.',
    link: 'https://www.educative.io/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:40:00Z'),
  },
  {
    name: '"Grokking Algorithms" by Aditya Bhargava',
    description: 'A visual and intuitive guide to understanding essential algorithms and data structures.',
    link: 'https://www.manning.com/books/grokking-algorithms',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:30:00Z'),
  },
  {
    name: '"Building Microservices" by Sam Newman',
    description: 'A practical guide for designing and building microservices-based architectures.',
    link: 'https://www.oreilly.com/library/view/building-microservices/9781491950340/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:20:00Z'),
  },
  {
    name: 'Refactoring.Guru',
    description: 'A paid online resource that explains refactoring patterns, design patterns, and SOLID principles in a visual and easy-to-understand way.',
    link: 'https://refactoring.guru/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:10:00Z'),
  },
  {
    name: 'Wes Bos Courses',
    description: 'Popular and well-produced courses on JavaScript, React, CSS Grid, Flexbox, and other web technologies.',
    link: 'https://wesbos.com/courses/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:00:00Z'),
  },
  {
    name: 'Egghead.io',
    description: 'Offers concise and focused video lessons for web developers, with a focus on JavaScript frameworks and modern tools.',
    link: 'https://egghead.io/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:50:00Z'),
  },
  // Books & Courses - Free Tier
  {
    name: 'freeCodeCamp',
    description: 'Offers thousands of hours of interactive programming content and free certifications in web development, data science, and more.',
    link: 'https://www.freecodecamp.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:40:00Z'),
  },
  {
    name: 'edX (Audit Track)',
    description: 'Allows auditing courses from renowned universities for free, without access to certificates or graded assignments.',
    link: 'https://www.edx.org/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:30:00Z'),
  },
  {
    name: 'Codecademy (Basic Plan)',
    description: 'Offers free interactive lessons to learn basic programming concepts in various languages.',
    link: 'https://www.codecademy.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:20:00Z'),
  },
  {
    name: 'Coursera (Audit Track)',
    description: 'Like edX, allows auditing many courses for free.',
    link: 'https://www.coursera.org/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:10:00Z'),
  },
  {
    name: 'Udemy (Free Courses Filter)',
    description: 'Has a section of completely free courses, usually introductory or promotional.',
    link: 'https://www.udemy.com/courses/free/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:00:00Z'),
  },
  {
    name: 'Google AI for Developers',
    description: 'Free courses and resources from Google to learn about Machine Learning, TensorFlow, and AI.',
    link: 'https://developers.google.com/machine-learning/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:50:00Z'),
  },
  {
    name: 'Microsoft Learn',
    description: 'Offers free learning modules and learning paths on Microsoft technologies, including Azure, .NET, and AI development.',
    link: 'https://learn.microsoft.com/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:40:00Z'),
  },
  {
    name: 'MIT OpenCourseware',
    description: 'University-level course materials from MIT available for free online, including computer science courses.',
    link: 'https://ocw.mit.edu/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:30:00Z'),
  },
  {
    name: 'W3Schools',
    description: 'A complete web resource for learning web programming languages (HTML, CSS, JavaScript, SQL, Python, etc.) with tutorials and examples.',
    link: 'https://www.w3schools.com/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:20:00Z'),
  },
  // Books & Courses - Open Source
  {
    name: 'The Odin Project',
    description: 'An open-source full-stack web development curriculum, with a focus on Ruby on Rails or JavaScript/React, that guides students through practical projects.',
    link: 'https://www.theodinproject.com/',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:10:00Z'),
  },
  {
    name: 'Exercism',
    description: 'A platform that offers programming challenges in dozens of languages, with free mentoring by volunteers.',
    link: 'https://exercism.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:00:00Z'),
  },
  {
    name: 'Hack The Box (Free Tier)',
    description: 'A cybersecurity platform that offers hands-on labs to learn and improve ethical hacking skills (free machines for use).',
    link: 'https://www.hackthebox.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:50:00Z'),
  },
  {
    name: '"You Don\'t Know JS Yet" (Book Series) by Kyle Simpson',
    description: 'An open-source book series on GitHub that delves deep into JavaScript, covering advanced topics.',
    link: 'https://github.com/getify/You-Dont-Know-JS',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:40:00Z'),
  },
  {
    name: 'Google\'s Python Class',
    description: 'A free course from Google for people with little programming experience, focusing on Python.',
    link: 'https://developers.google.com/edu/python/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:30:00Z'),
  },
  {
    name: 'Learn Git Branching',
    description: 'An interactive and visual tutorial for learning Git Branching, essential for version control.',
    link: 'https://learngitbranching.js.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:20:00Z'),
  },
  {
    name: 'Open Source Society University (OSSU)',
    description: 'A curated curriculum of free online courses for a university-level computer science education.',
    link: 'https://github.com/ossu/computer-science',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:10:00Z'),
  },
  {
    name: 'HackerRank (Community Challenges)',
    description: 'A platform with programming and algorithm challenges to practice and improve skills, with many free problems and courses.',
    link: 'https://www.hackerrank.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:00:00Z'),
  },
  {
    name: 'LeetCode (Free Problems)',
    description: 'A popular platform for practicing algorithm and data structure problems, essential for tech job interviews (many problems are free).',
    link: 'https://leetcode.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:50:00Z'),
  },
  {
    name: 'The Missing Semester of Your CS Education (MIT)',
    description: 'A short, free course from MIT focused on practical tools and skills not taught in traditional CS curricula.',
    link: 'https://missing.csail.mit.edu/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:40:00Z'),
  },
  {
    name: 'Roadmap.sh',
    description: 'Collections of learning roadmaps for developers, covering different specializations (frontend, backend, DevOps, etc.), open-source.',
    link: 'https://roadmap.sh/',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:30:00Z'),
  },
  {
    name: 'MDN Web Docs (Mozilla)',
    description: 'Comprehensive documentation and tutorials on web technologies (HTML, CSS, JavaScript, Web APIs), an essential and free resource for developers.',
    link: 'https://developer.mozilla.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:20:00Z'),
  },
  {
    name: 'dev.to',
    description: 'A community of developers where they share articles and tutorials on various technologies, many of them step-by-step guides.',
    link: 'https://dev.to/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:10:00Z'),
  },
  
  // UI & Design - Paid
  {
    name: 'Figma (Professional/Organization Plans)',
    description: 'A collaborative design platform for creating user interfaces, prototypes, and design systems. Paid plans offer advanced features for teams.',
    link: 'https://www.figma.com/pricing/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T10:00:00Z'),
  },
  {
    name: 'Sketch',
    description: 'A vector graphics editor exclusively for macOS, widely used for UI/UX design, with a paid license model.',
    link: 'https://www.sketch.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:50:00Z'),
  },
  {
    name: 'Adobe XD',
    description: 'A user experience design tool for designing and prototyping user interfaces for web and apps, part of the Creative Cloud.',
    link: 'https://www.adobe.com/products/xd.html',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:40:00Z'),
  },
  {
    name: 'InVision',
    description: 'A platform for interactive prototyping, design workflow, and collaboration, with paid plans for larger teams and advanced features.',
    link: 'https://www.invisionapp.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:30:00Z'),
  },
  {
    name: 'Principle (macOS)',
    description: 'A simple and powerful animation and interactive prototyping design tool for user interfaces.',
    link: 'https://principleformac.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:20:00Z'),
  },
  {
    name: 'Axure RP',
    description: 'A robust tool for wireframing, prototyping, and specification, focused on complex and interactive designs.',
    link: 'https://www.axure.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:10:00Z'),
  },
  {
    name: 'Zeplin',
    description: 'A collaboration tool that connects designers and developers, exporting designs and providing specifications, assets, and code snippets.',
    link: 'https://zeplin.io/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:00:00Z'),
  },
  {
    name: 'UXPin',
    description: 'An end-to-end product design platform that allows you to design, prototype, and document user experiences.',
    link: 'https://www.uxpin.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:50:00Z'),
  },
  {
    name: 'Affinity Designer',
    description: 'A vector and raster graphics editor alternative to Adobe Illustrator, known for its performance and one-time price.',
    link: 'https://affinity.serif.com/en-us/designer/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:40:00Z'),
  },
  {
    name: 'Flinto (macOS)',
    description: 'A tool for creating interactive prototypes and micro-interactions for iOS, Android, and web.',
    link: 'https://www.flinto.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:30:00Z'),
  },
  // UI & Design - Free Tier
  {
    name: 'Figma (Starter Plan)',
    description: 'Offers a free plan for individual use with essential design and prototyping features.',
    link: 'https://www.figma.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:20:00Z'),
  },
  {
    name: 'Canva (Free Plan)',
    description: 'An online graphic design tool for creating a variety of visual materials, including social media graphics and presentations, with many free templates.',
    link: 'https://www.canva.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:10:00Z'),
  },
  {
    name: 'Miro (Free Plan)',
    description: 'A collaborative online whiteboard for brainstorming, diagramming, planning, and design thinking workshops. The free plan is limited.',
    link: 'https://miro.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:00:00Z'),
  },
  {
    name: 'Whimsical',
    description: 'Combines wireframes, flowcharts, sticky notes, and documents in a fast visual collaboration tool. Offers a limited free plan.',
    link: 'https://whimsical.com/pricing',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:50:00Z'),
  },
  {
    name: 'Marvel',
    description: 'A design prototyping and collaboration platform that allows you to turn mockups into interactive prototypes. Has a free plan for one project.',
    link: 'https://marvelapp.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:40:00Z'),
  },
  {
    name: 'Font Awesome (Free Icons)',
    description: 'A popular library of scalable vector-based icons that can be customized with CSS. The free version has many icons.',
    link: 'https://fontawesome.com/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:30:00Z'),
  },
  {
    name: 'Google Fonts',
    description: 'A vast library of free and open-source fonts optimized for the web, which can be used freely in any project.',
    link: 'https://fonts.google.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:20:00Z'),
  },
  // UI & Design - Open Source
  {
    name: 'GIMP (GNU Image Manipulation Program)',
    description: 'A powerful open-source image editor, a free alternative to Photoshop, for photo manipulation, image composition, and art creation.',
    link: 'https://www.gimp.org/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:10:00Z'),
  },
  {
    name: 'Inkscape',
    description: 'An open-source vector graphics editor, ideal for creating illustrations, diagrams, line art, web graphics, and more.',
    link: 'https://inkscape.org/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:00:00Z'),
  },
  {
    name: 'Blender',
    description: 'Open-source software for 3D modeling, animation, rendering, compositing, motion tracking, video editing, and 2D animation pipeline.',
    link: 'https://www.blender.org/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:50:00Z'),
  },
  {
    name: 'Penpot',
    description: 'An open-source, web-based prototyping and design platform, a competitor to Figma.',
    link: 'https://penpot.app/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:40:00Z'),
  },
  {
    name: 'UI Libraries & Component Frameworks',
    description: 'Open-source UI component libraries that provide ready-to-use building blocks for web interfaces (e.g., Material-UI, Ant Design, Bootstrap).',
    link: 'https://mui.com/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:30:00Z'),
  },
  {
    name: 'Unsplash',
    description: 'A vast database of high-resolution photos free to use in design projects.',
    link: 'https://unsplash.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:20:00Z'),
  },
  {
    name: 'Pexels',
    description: 'Similar to Unsplash, offers high-quality stock photos and videos, free to use.',
    link: 'https://www.pexels.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:10:00Z'),
  },
  {
    name: 'Open Peeps',
    description: 'A library of hand-drawn illustrations of people, combinable to create various poses and scenarios. Free for personal and commercial use.',
    link: 'https://www.openpeeps.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:00:00Z'),
  },
  {
    name: 'Lucide Icons',
    description: 'An open-source library of clean, customizable, and consistent icons, ideal for user interfaces.',
    link: 'https://lucide.dev/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T05:50:00Z'),
  },
];
Obrigado pelo seu tempo e atenção. Sem pressa, quando tiver um tempo para analisar e implementar, será ótimo.