
'use server';

import { db } from '@/lib/firebase';
import type { Resource } from '@/types';
import { 
  collection, 
  getDocs, 
  getDoc, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  doc,
  orderBy, 
  Timestamp,
  serverTimestamp,
  query
} from 'firebase/firestore';
import { revalidatePath } from 'next/cache';

const sampleResources: Omit<Resource, 'id'>[] = [
  // AI & Machine Learning
  {
    name: 'OpenAI GPT-4 API',
    description: 'Acesso à API do modelo de linguagem mais avançado da OpenAI para diversas aplicações, de geração de texto a análise.',
    link: 'https://openai.com/gpt-4/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T10:00:00Z'),
  },
  {
    name: 'Google Cloud AI Platform',
    description: 'Conjunto de serviços de ML gerenciados que permite construir, treinar e implantar modelos em escala.',
    link: 'https://cloud.google.com/ai-platform/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:50:00Z'),
  },
  {
    name: 'AWS SageMaker',
    description: 'Serviço de ML totalmente gerenciado que ajuda desenvolvedores e cientistas de dados a construir, treinar e implantar modelos rapidamente.',
    link: 'https://aws.amazon.com/sagemaker/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:40:00Z'),
  },
  {
    name: 'Azure Machine Learning',
    description: 'Plataforma de nuvem para acelerar o ciclo de vida de aprendizado de máquina, incluindo treinamento, implantação e gerenciamento de modelos.',
    link: 'https://azure.microsoft.com/en-us/products/machine-learning/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:30:00Z'),
  },
  {
    name: 'Hugging Face Hub (Models & Inference APIs)',
    description: 'Embora tenha muitos modelos gratuitos, oferece Inference APIs pagas para uso em produção de modelos populares.',
    link: 'https://huggingface.co/docs/api-inference/pricing',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:20:00Z'),
  },
  {
    name: 'Cohere API',
    description: 'Oferece modelos de linguagem grandes e poderosos para geração, incorporação e pesquisa, com planos pagos para uso comercial.',
    link: 'https://cohere.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:10:00Z'),
  },
  {
    name: 'Weights & Biases',
    description: 'Plataforma para rastreamento, visualização e colaboração em experimentos de aprendizado de máquina. Oferece planos pagos para equipes.',
    link: 'https://wandb.ai/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T09:00:00Z'),
  },
  {
    name: 'RunwayML',
    description: 'Plataforma para criação de conteúdo visual usando IA (geração de vídeo, imagem, edição), com planos pagos para recursos avançados e maior uso.',
    link: 'https://runwayml.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:50:00Z'),
  },
  {
    name: 'Midjourney',
    description: 'Gerador de imagens a partir de texto (text-to-image) de alta qualidade, operado via Discord, com planos de assinatura.',
    link: 'https://www.midjourney.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:40:00Z'),
  },
  {
    name: 'Replicate',
    description: 'Permite rodar modelos de IA no cloud com uma API simples, pagando apenas pelo uso, com diversos modelos pré-treinados e a possibilidade de subir os seus.',
    link: 'https://replicate.com/',
    category: 'AI & Machine Learning',
    pricing: 'Paid',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:30:00Z'),
  },
  {
    name: 'Google Colab',
    description: 'Permite escrever e executar código Python no navegador, com acesso gratuito a GPUs e TPUs para ML.',
    link: 'https://colab.research.google.com/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:20:00Z'),
  },
  {
    name: 'Kaggle',
    description: 'Plataforma de competições de ciência de dados que oferece notebooks gratuitos com GPUs para experimentos de ML e acesso a grandes conjuntos de dados.',
    link: 'https://www.kaggle.com/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:10:00Z'),
  },
  {
    name: 'TensorFlow Lite',
    description: 'Permite executar modelos de TensorFlow em dispositivos móveis e embarcados, com ferramentas e modelos pré-treinados para uso gratuito.',
    link: 'https://www.tensorflow.org/lite/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T08:00:00Z'),
  },
  {
    name: 'PyTorch Mobile',
    description: 'Ferramenta para levar modelos PyTorch para dispositivos móveis, com a estrutura para desenvolvimento e inferência gratuita.',
    link: 'https://pytorch.org/mobile/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:50:00Z'),
  },
  {
    name: 'Roboflow',
    description: 'Plataforma para construção de datasets para visão computacional, com um plano gratuito para projetos e inferência limitados.',
    link: 'https://roboflow.com/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:40:00Z'),
  },
  {
    name: 'Hugging Face Hub (Model Repository)',
    description: 'Milhares de modelos pré-treinados e datasets abertos disponíveis para download e uso gratuito (Inferência via API pode ser paga, mas o download e uso local é gratuito).',
    link: 'https://huggingface.co/models',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:30:00Z'),
  },
  {
    name: 'Google Cloud AI Platform (Free Tier)',
    description: 'Oferece créditos e limites de uso gratuitos para alguns serviços de ML, ideal para experimentação.',
    link: 'https://cloud.google.com/free/docs/gcp-free-tier#ai-ml',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:20:00Z'),
  },
  {
    name: 'AWS Free Tier (SageMaker, Rekognition, etc.)',
    description: 'Diversos serviços de IA/ML na AWS possuem uma camada gratuita para novos usuários, permitindo experimentar antes de pagar.',
    link: 'https://aws.amazon.com/free/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:10:00Z'),
  },
  {
    name: 'Azure Free Account (Azure ML, Cognitive Services)',
    description: 'Conta gratuita da Azure com créditos e serviços de IA/ML que podem ser usados sem custo por um tempo.',
    link: 'https://azure.microsoft.com/en-us/free/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T07:00:00Z'),
  },
  {
    name: 'Gradio',
    description: 'Biblioteca Python para construir interfaces de usuário rápidas para modelos de ML, permitindo demonstrações interativas de forma gratuita.',
    link: 'https://www.gradio.app/',
    category: 'AI & Machine Learning',
    pricing: 'Free Tier',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:50:00Z'),
  },
  {
    name: 'TensorFlow',
    description: 'Biblioteca open source completa para aprendizado de máquina, desenvolvida pelo Google, amplamente utilizada para pesquisa e produção.',
    link: 'https://www.tensorflow.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:40:00Z'),
  },
  {
    name: 'PyTorch',
    description: 'Framework open source de aprendizado de máquina desenvolvido pelo Facebook (Meta), conhecido por sua flexibilidade e facilidade de uso.',
    link: 'https://pytorch.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:30:00Z'),
  },
  {
    name: 'scikit-learn',
    description: 'Biblioteca Python para aprendizado de máquina clássico (classificação, regressão, clustering), fácil de usar e com excelente documentação.',
    link: 'https://scikit-learn.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:20:00Z'),
  },
  {
    name: 'Keras',
    description: 'API de alto nível para construir e treinar modelos de deep learning, que pode rodar em cima de TensorFlow ou PyTorch.',
    link: 'https://keras.io/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:10:00Z'),
  },
  {
    name: 'Jupyter Notebook / Lab',
    description: 'Ambiente de computação interativo open source que permite criar e compartilhar documentos que contêm código, equações, visualizações e texto narrativo.',
    link: 'https://jupyter.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T06:00:00Z'),
  },
  {
    name: 'MLflow',
    description: 'Plataforma open source para gerenciar o ciclo de vida do ML, incluindo experimentação, reprodutibilidade e implantação.',
    link: 'https://mlflow.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:50:00Z'),
  },
  {
    name: 'OpenMMLab',
    description: 'Coleção de ferramentas e benchmarks open source para pesquisa em visão computacional, incluindo detecção de objetos, segmentação e mais.',
    link: 'https://openmmlab.com/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:40:00Z'),
  },
  {
    name: 'FastAI',
    description: 'Biblioteca open source que facilita o treinamento de modelos de deep learning de última geração com uma API de alto nível, construída sobre PyTorch.',
    link: 'https://www.fast.ai/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:30:00Z'),
  },
  {
    name: 'Apache MXNet',
    description: 'Framework de deep learning open source, escalável e flexível, que suporta múltiplos idiomas de programação.',
    link: 'https://mxnet.apache.org/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:20:00Z'),
  },
  {
    name: 'ONNX (Open Neural Network Exchange)',
    description: 'Formato open source para representar modelos de aprendizado de máquina, permitindo a interoperabilidade entre diferentes frameworks.',
    link: 'https://onnx.ai/',
    category: 'AI & Machine Learning',
    pricing: 'Open Source',
    icon: 'BrainCircuit',
    createdAt: new Date('2024-05-22T05:10:00Z'),
  },

  // Developer Tools
  {
    name: 'JetBrains IntelliJ IDEA Ultimate',
    description: 'Uma IDE poderosa para desenvolvimento Java, Kotlin, Scala e outras linguagens, com recursos avançados para Spring, bancos de dados, etc.',
    link: 'https://www.jetbrains.com/idea/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T10:00:00Z'),
  },
  {
    name: 'Sublime Text',
    description: 'Um editor de código sofisticado e rápido, conhecido por sua interface de usuário elegante, alto desempenho e plugins robustos.',
    link: 'https://www.sublimetext.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:50:00Z'),
  },
  {
    name: 'Postman',
    description: 'Plataforma de colaboração para desenvolvimento de APIs, permitindo projetar, testar, documentar e monitorar APIs. Oferece planos pagos para equipes e recursos avançados.',
    link: 'https://www.postman.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:40:00Z'),
  },
  {
    name: 'TablePlus',
    description: 'Um moderno cliente de banco de dados nativo para macOS, Windows, Linux, que suporta múltiplos bancos de dados com uma GUI limpa.',
    link: 'https://tableplus.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:30:00Z'),
  },
  {
    name: 'Fiddler Everywhere',
    description: 'Proxy de depuração web que permite inspecionar, depurar e modificar tráfego HTTP/HTTPS entre um computador e a internet.',
    link: 'https://www.telerik.com/fiddler/fiddler-everywhere/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:20:00Z'),
  },
  {
    name: 'DataGrip (JetBrains)',
    description: 'Uma IDE de banco de dados que oferece suporte a vários DBMSs, proporcionando uma experiência unificada para desenvolvimento de banco de dados.',
    link: 'https://www.jetbrains.com/datagrip/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:10:00Z'),
  },
  {
    name: 'Tower',
    description: 'Cliente Git GUI (interface gráfica do usuário) para Mac e Windows, que simplifica o uso do Git com uma interface visual intuitiva.',
    link: 'https://www.git-tower.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T09:00:00Z'),
  },
  {
    name: 'WebStorm (JetBrains)',
    description: 'Uma IDE poderosa para desenvolvimento JavaScript, TypeScript, HTML e CSS, ideal para frameworks front-end como React, Angular e Vue.',
    link: 'https://www.jetbrains.com/webstorm/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:50:00Z'),
  },
  {
    name: 'Beyond Compare',
    description: 'Ferramenta de comparação de arquivos e pastas que permite comparar e mesclar arquivos de texto, pastas, arquivos zip e FTP.',
    link: 'https://www.scootersoftware.com/',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:40:00Z'),
  },
  {
    name: 'Dash',
    description: 'Um navegador de documentação e gerenciador de snippets de código para desenvolvedores, com acesso offline a mais de 200 conjuntos de documentos APIs.',
    link: 'https://kapeli.com/dash',
    category: 'Developer Tools',
    pricing: 'Paid',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:30:00Z'),
  },
  {
    name: 'Postman (Free Tier)',
    description: 'Permite o uso básico para indivíduos e pequenas equipes, incluindo coleções de API, testes e documentação limitada.',
    link: 'https://www.postman.com/pricing/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:20:00Z'),
  },
  {
    name: 'GitHub Desktop',
    description: 'Aplicativo de desktop open source que simplifica o fluxo de trabalho do Git e GitHub, tornando a colaboração mais fácil.',
    link: 'https://desktop.github.com/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:10:00Z'),
  },
  {
    name: 'Insomnia',
    description: 'Um cliente de API REST e GraphQL de código aberto, com recursos de design, depuração e teste de APIs. Oferece funcionalidades gratuitas robustas.',
    link: 'https://insomnia.rest/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T08:00:00Z'),
  },
  {
    name: 'DBeaver Community Edition',
    description: 'Um cliente universal de banco de dados open source com uma GUI para múltiplos bancos de dados.',
    link: 'https://dbeaver.io/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:50:00Z'),
  },
  {
    name: 'Sentry (Free Tier)',
    description: 'Monitoramento de erros em tempo real que ajuda a descobrir, triar e priorizar erros em seu código em produção, com um plano gratuito para pequenos projetos.',
    link: 'https://sentry.io/pricing/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'Component',
    createdAt: new Date('2024-05-21T07:40:00Z'),
  },
  {
    name: 'CodeSandbox',
    description: 'Um ambiente de desenvolvimento online para projetos web, com foco em desenvolvimento front-end e prototipagem, oferecendo um plano gratuito.',
    link: 'https://codesandbox.io/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:30:00Z'),
  },
  {
    name: 'Ngrok',
    description: 'Cria túneis seguros para sua máquina local a partir da internet, ótimo para testar webhooks ou compartilhar um ambiente de desenvolvimento local, com uma camada gratuita.',
    link: 'https://ngrok.com/',
    category: 'Developer Tools',
    pricing: 'Free Tier',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:20:00Z'),
  },
  {
    name: 'VS Code (Visual Studio Code)',
    description: 'Um editor de código-fonte leve, mas poderoso, com suporte a milhares de extensões, tornando-o extremamente versátil para qualquer linguagem.',
    link: 'https://code.visualstudio.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:10:00Z'),
  },
  {
    name: 'Git',
    description: 'O sistema de controle de versão distribuído mais amplamente usado, essencial para o desenvolvimento colaborativo.',
    link: 'https://git-scm.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T07:00:00Z'),
  },
  {
    name: 'Docker',
    description: 'Plataforma open source para desenvolver, enviar e executar aplicativos usando contêineres.',
    link: 'https://www.docker.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-21T06:50:00Z'),
  },
  {
    name: 'Node.js',
    description: 'Ambiente de tempo de execução JavaScript open source que permite construir aplicativos de rede escaláveis e de alto desempenho.',
    link: 'https://nodejs.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:40:00Z'),
  },
  {
    name: 'Python',
    description: 'Linguagem de programação open source popular para desenvolvimento web, ciência de dados, IA, automação e muito mais.',
    link: 'https://www.python.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:30:00Z'),
  },
  {
    name: 'Kubernetes',
    description: 'Sistema open source para automatizar a implantação, escalamento e gerenciamento de aplicativos conteinerizados.',
    link: 'https://kubernetes.io/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-21T06:20:00Z'),
  },
  {
    name: 'ESLint',
    description: 'Ferramenta de linting para JavaScript e JSX, que ajuda a identificar e corrigir problemas em seu código.',
    link: 'https://eslint.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:10:00Z'),
  },
  {
    name: 'Prettier',
    description: 'Um formatador de código opinativo que impõe um estilo consistente em todo o seu projeto, eliminando discussões de estilo.',
    link: 'https://prettier.io/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T06:00:00Z'),
  },
  {
    name: 'Webpack',
    description: 'Um bundler de módulos open source para JavaScript, que empacota ativos para uso em um navegador.',
    link: 'https://webpack.js.org/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T05:50:00Z'),
  },
  {
    name: 'Vagrant',
    description: 'Ferramenta open source para construir e gerenciar ambientes de máquinas virtuais portáteis e replicáveis.',
    link: 'https://www.vagrantup.com/',
    category: 'Developer Tools',
    pricing: 'Open Source',
    icon: 'TerminalSquare',
    createdAt: new Date('2024-05-21T05:40:00Z'),
  },

  // DevOps & Hosting
  {
    name: 'AWS (Amazon Web Services)',
    description: 'A maior plataforma de nuvem do mundo, oferecendo uma vasta gama de serviços para computação, armazenamento, bancos de dados, analytics, machine learning, e mais.',
    link: 'https://aws.amazon.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T10:00:00Z'),
  },
  {
    name: 'Google Cloud Platform (GCP)',
    description: 'Oferece uma suite de serviços de computação em nuvem, incluindo IaaS, PaaS e ambientes serverless, com forte integração com ferramentas de ML.',
    link: 'https://cloud.google.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:50:00Z'),
  },
  {
    name: 'Microsoft Azure',
    description: 'Uma plataforma de computação em nuvem que fornece serviços de desenvolvimento, computação, rede, análise, armazenamento, e mais.',
    link: 'https://azure.microsoft.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:40:00Z'),
  },
  {
    name: 'DigitalOcean',
    description: 'Um provedor de infraestrutura de nuvem simples e escalável, popular entre desenvolvedores por seus "Droplets" (VMs) e interfaces amigáveis.',
    link: 'https://www.digitalocean.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:30:00Z'),
  },
  {
    name: 'Vercel',
    description: 'Plataforma para Static Sites e Serverless Functions, otimizada para frameworks React, Next.js, Vue, Nuxt, com foco em alta performance e DX (Developer Experience).',
    link: 'https://vercel.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:20:00Z'),
  },
  {
    name: 'GitLab CI/CD',
    description: 'Parte integrante do GitLab, oferece uma solução CI/CD robusta, integrada ao gerenciamento de código e outras ferramentas DevOps. Planos pagos com mais recursos.',
    link: 'https://docs.gitlab.com/ee/ci/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:10:00Z'),
  },
  {
    name: 'Datadog',
    description: 'Plataforma de monitoramento e segurança para aplicações em nuvem em larga escala, oferecendo observabilidade de infraestrutura, logs e APM (Application Performance Monitoring).',
    link: 'https://www.datadoghq.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T09:00:00Z'),
  },
  {
    name: 'New Relic',
    description: 'Plataforma de observabilidade que ajuda a entender e otimizar o desempenho de softwares complexos em produção.',
    link: 'https://newrelic.com/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:50:00Z'),
  },
  {
    name: 'HashiCorp Vault',
    description: 'Ferramenta para gerenciar segredos e proteger dados sensíveis em ambientes modernos de DevOps. Oferece versões pagas com recursos de nível empresarial.',
    link: 'https://www.hashicorp.com/products/vault',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:40:00Z'),
  },
  {
    name: 'JFrog Artifactory',
    description: 'Um repositório binário universal que gerencia todos os artefatos de software, com planos pagos para empresas e equipes maiores.',
    link: 'https://jfrog.com/artifactory/',
    category: 'DevOps & Hosting',
    pricing: 'Paid',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:30:00Z'),
  },
  {
    name: 'Netlify',
    description: 'Oferece um plano gratuito generoso para hospedar sites estáticos e Single Page Applications, com CI/CD, HTTPS, e funções serverless limitadas.',
    link: 'https://www.netlify.com/pricing/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:20:00Z'),
  },
  {
    name: 'Vercel (Hobby Plan)',
    description: 'Permite hospedar projetos pessoais e não comerciais gratuitamente, com CI/CD e funções serverless.',
    link: 'https://vercel.com/pricing',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:10:00Z'),
  },
  {
    name: 'Render',
    description: 'Oferece uma camada gratuita para serviços web estáticos, bancos de dados e mais, facilitando a implantação de diversos tipos de aplicativos.',
    link: 'https://render.com/pricing',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T08:00:00Z'),
  },
  {
    name: 'Cloudflare Workers',
    description: 'Permite executar código JavaScript na rede global da Cloudflare com um plano gratuito generoso para requisições diárias, ideal para borda.',
    link: 'https://www.cloudflare.com/lp/workers-free/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:50:00Z'),
  },
  {
    name: 'GitHub Actions',
    description: 'O serviço CI/CD integrado ao GitHub oferece um número significativo de minutos de execução gratuitos por mês para repositórios públicos e privados.',
    link: 'https://github.com/features/actions',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:40:00Z'),
  },
  {
    name: 'GitLab CI/CD (Free Tier)',
    description: 'A versão gratuita do GitLab (self-managed ou GitLab.com) inclui funcionalidades CI/CD completas para repositórios públicos e privados com limites de minutos.',
    link: 'https://about.gitlab.com/pricing/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:30:00Z'),
  },
  {
    name: 'Firebase Hosting',
    description: 'Parte do Firebase, oferece hospedagem rápida e segura para conteúdo web com um generoso plano gratuito (Spark Plan).',
    link: 'https://firebase.google.com/docs/hosting/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:20:00Z'),
  },
  {
    name: 'Docker Hub (Free Tier)',
    description: 'Repositório de imagens Docker que permite armazenar e compartilhar imagens de contêineres, com um plano gratuito para uso individual.',
    link: 'https://hub.docker.com/',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:10:00Z'),
  },
  {
    name: 'Logtail (Better Stack)',
    description: 'Monitoramento de logs em tempo real com uma camada gratuita que inclui um volume limitado de logs e retenção.',
    link: 'https://betterstack.com/logtail/pricing',
    category: 'DevOps & Hosting',
    pricing: 'Free Tier',
    icon: 'Server',
    createdAt: new Date('2024-05-20T07:00:00Z'),
  },
  {
    name: 'Jenkins',
    description: 'Servidor de automação open source líder para CI/CD, flexível e com milhares de plugins.',
    link: 'https://www.jenkins.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:50:00Z'),
  },
  {
    name: 'Ansible',
    description: 'Ferramenta open source de automação de TI para gerenciamento de configuração, implantação de aplicativos e orquestração.',
    link: 'https://www.ansible.com/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:40:00Z'),
  },
  {
    name: 'Prometheus',
    description: 'Sistema open source de monitoramento e alerta de sistemas em tempo real, popular em ambientes de nuvem nativa.',
    link: 'https://prometheus.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:30:00Z'),
  },
  {
    name: 'Grafana',
    description: 'Ferramenta open source para visualização e análise de dados, comumente usada em conjunto com Prometheus para criar dashboards de monitoramento.',
    link: 'https://grafana.com/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:20:00Z'),
  },
  {
    name: 'Terraform',
    description: 'Ferramenta open source de Infraestrutura como Código (IaC) que permite provisionar e gerenciar infraestrutura em diversas nuvens.',
    link: 'https://www.terraform.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:10:00Z'),
  },
  {
    name: 'Nagios',
    description: 'Sistema de monitoramento open source que permite monitorar sistemas, redes e infraestrutura.',
    link: 'https://www.nagios.org/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T06:00:00Z'),
  },
  {
    name: 'ELK Stack (Elasticsearch, Logstash, Kibana)',
    description: 'Conjunto de ferramentas open source para ingestão, armazenamento, busca e visualização de logs e dados.',
    link: 'https://www.elastic.co/elk-stack/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T05:50:00Z'),
  },
  {
    name: 'Argo CD',
    description: 'Uma ferramenta de implantação contínua (CD) declarativa e baseada em GitOps para Kubernetes.',
    link: 'https://argocd.readthedocs.io/',
    category: 'DevOps & Hosting',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-20T05:40:00Z'),
  },

  // Productivity
  {
    name: 'Notion',
    description: 'Um espaço de trabalho tudo-em-um para anotações, gerenciamento de projetos, bancos de dados, wikis e colaboração, amplamente utilizado por desenvolvedores e equipes.',
    link: 'https://www.notion.so/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T10:00:00Z'),
  },
  {
    name: 'Todoist',
    description: 'Um aplicativo de lista de tarefas e gerenciamento de projetos que ajuda a organizar o trabalho e a vida pessoal, com recursos avançados para produtividade.',
    link: 'https://todoist.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:50:00Z'),
  },
  {
    name: 'Forest',
    description: 'Um aplicativo de produtividade que ajuda a focar e evitar distrações, plantando uma árvore virtual enquanto você se concentra.',
    link: 'https://www.forestapp.cc/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:40:00Z'),
  },
  {
    name: 'ClickUp',
    description: 'Uma plataforma de gerenciamento de projetos e produtividade que centraliza tarefas, documentos, metas e chat em um único lugar.',
    link: 'https://clickup.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:30:00Z'),
  },
  {
    name: 'RescueTime',
    description: 'Um aplicativo de rastreamento de tempo automático que monitora suas atividades no computador e fornece relatórios detalhados sobre como você gasta seu tempo.',
    link: 'https://www.rescuetime.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:20:00Z'),
  },
  {
    name: 'Things 3 (macOS/iOS)',
    description: 'Um gerenciador de tarefas premiado, conhecido por seu design limpo, interface intuitiva e foco em ajudar você a realizar as coisas.',
    link: 'https://culturedcode.com/things/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:10:00Z'),
  },
  {
    name: 'Dashlane',
    description: 'Gerenciador de senhas e carteira digital que ajuda a proteger suas contas online e preencher formulários automaticamente, aumentando a segurança e a produtividade.',
    link: 'https://www.dashlane.com/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T09:00:00Z'),
  },
  {
    name: 'Krisp',
    description: 'Um aplicativo de cancelamento de ruído baseado em IA que remove ruídos de fundo de chamadas e reuniões, melhorando a clareza da comunicação.',
    link: 'https://krisp.ai/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:50:00Z'),
  },
  {
    name: 'Figma (Professional/Organization Plans)',
    description: 'Embora tenha uma camada gratuita, os planos pagos oferecem recursos avançados de colaboração, prototipagem e design system para equipes maiores.',
    link: 'https://www.figma.com/pricing/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-19T08:40:00Z'),
  },
  {
    name: 'Linear',
    description: 'Um rastreador de problemas e ferramenta de gerenciamento de projetos focado em equipes de software de alto desempenho, conhecido por sua velocidade e simplicidade.',
    link: 'https://linear.app/',
    category: 'Productivity',
    pricing: 'Paid',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:30:00Z'),
  },
  {
    name: 'Asana (Basic Plan)',
    description: 'Ferramenta de gerenciamento de projetos e tarefas que permite que equipes organizem, rastreiem e gerenciem seus trabalhos. O plano básico é gratuito para equipes menores.',
    link: 'https://asana.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:20:00Z'),
  },
  {
    name: 'Trello',
    description: 'Ferramenta de gerenciamento de projetos baseada em quadros Kanban, ideal para organização visual de tarefas e fluxos de trabalho. Oferece um plano gratuito robusto.',
    link: 'https://trello.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:10:00Z'),
  },
  {
    name: 'Evernote (Free Plan)',
    description: 'Aplicativo de anotações que permite capturar ideias, organizar notas e gerenciar tarefas, com um plano gratuito limitado.',
    link: 'https://evernote.com/compare-plans',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T08:00:00Z'),
  },
  {
    name: 'Slack (Free Plan)',
    description: 'Plataforma de comunicação para equipes, que permite conversas em tempo real, compartilhamento de arquivos e integração com outras ferramentas. O plano gratuito é para uso básico.',
    link: 'https://slack.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:50:00Z'),
  },
  {
    name: 'Microsoft To Do',
    description: 'Um aplicativo de lista de tarefas simples e inteligente que ajuda a planejar o dia e gerenciar tarefas de forma eficaz, sincronizado com o Outlook. Gratuito com conta Microsoft.',
    link: 'https://todo.microsoft.com/',
    category: 'Productivity',
    pricing: 'Free',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:40:00Z'),
  },
  {
    name: 'Notion (Free Personal Plan)',
    description: 'Acesso gratuito a recursos básicos de anotações, wikis e gerenciamento de projetos para uso individual.',
    link: 'https://www.notion.so/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:30:00Z'),
  },
  {
    name: 'Google Workspace (Free Apps)',
    description: 'As versões gratuitas de Docs, Sheets, Slides, Calendar, Gmail, etc., são ferramentas de produtividade essenciais.',
    link: 'https://workspace.google.com/',
    category: 'Productivity',
    pricing: 'Free',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:20:00Z'),
  },
  {
    name: 'Zoom (Basic Plan)',
    description: 'Plataforma de videoconferência que oferece reuniões gratuitas com duração limitada e número de participantes.',
    link: 'https://zoom.us/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:10:00Z'),
  },
  {
    name: 'Grammarly (Free Version)',
    description: 'Ferramenta de escrita que verifica gramática, ortografia, pontuação e estilo, ajudando a melhorar a clareza da comunicação escrita.',
    link: 'https://www.grammarly.com/premium',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T07:00:00Z'),
  },
  {
    name: 'Calendly (Basic Plan)',
    description: 'Ferramenta de agendamento que simplifica a marcação de reuniões, permitindo que outros reservem horários em sua agenda disponível.',
    link: 'https://calendly.com/pricing',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:50:00Z'),
  },
  {
    name: 'Joplin',
    description: 'Um aplicativo de anotações e lista de tarefas open source com sincronização em nuvem e suporte a Markdown.',
    link: 'https://joplinapp.org/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:40:00Z'),
  },
  {
    name: 'Standard Notes',
    description: 'Um aplicativo de anotações e-mail simples, privado e open source, com foco em segurança e criptografia.',
    link: 'https://standardnotes.com/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:30:00Z'),
  },
  {
    name: 'Obsidian',
    description: 'Um poderoso software de base de conhecimento open source que funciona sobre um diretório local de arquivos Markdown, ideal para conectar ideias.',
    link: 'https://obsidian.md/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:20:00Z'),
  },
  {
    name: 'Nextcloud',
    description: 'Uma suíte de ferramentas de produtividade open source, incluindo armazenamento de arquivos, comunicação e colaboração, que você pode hospedar em seu próprio servidor.',
    link: 'https://nextcloud.com/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:10:00Z'),
  },
  {
    name: 'Mattermost',
    description: 'Uma plataforma de colaboração open source alternativa ao Slack, para equipes que precisam de comunicação segura e privada.',
    link: 'https://mattermost.com/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T06:00:00Z'),
  },
  {
    name: 'Self-hosted GitLab',
    description: 'Além do CI/CD, o GitLab (versão self-hosted) é uma plataforma completa de DevOps que inclui gerenciamento de projetos, wikis e muito mais, tudo open source.',
    link: 'https://about.gitlab.com/install/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Server',
    createdAt: new Date('2024-05-19T05:50:00Z'),
  },
  {
    name: 'KanbanFlow',
    description: 'Uma ferramenta online de quadro Kanban com recursos de rastreamento de tempo e Pomodoro, com uma versão gratuita e completa.',
    link: 'https://kanbanflow.com/',
    category: 'Productivity',
    pricing: 'Free Tier',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:40:00Z'),
  },
  {
    name: 'FocusWriter',
    description: 'Um editor de texto simples e sem distrações para escritores, projetado para ajudá-lo a focar na escrita.',
    link: 'https://gottcode.org/focuswriter/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:30:00Z'),
  },
  {
    name: 'OpenProject',
    description: 'Um software de gerenciamento de projetos open source para equipes que buscam planejamento de projetos, gerenciamento de tarefas e acompanhamento de tempo.',
    link: 'https://www.openproject.org/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:20:00Z'),
  },
  {
    name: 'Draw.io (diagrams.net)',
    description: 'Um editor de diagramas open source gratuito que pode ser usado online ou offline para criar fluxogramas, diagramas UML e mais.',
    link: 'https://app.diagrams.net/',
    category: 'Productivity',
    pricing: 'Open Source',
    icon: 'Zap',
    createdAt: new Date('2024-05-19T05:10:00Z'),
  },

  // Books & Courses
  {
    name: '"Clean Code" by Robert C. Martin',
    description: 'Um livro clássico que aborda os princípios de escrita de código limpo e de fácil manutenção.',
    link: 'https://www.oreilly.com/library/view/clean-code/9780136083238/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T10:00:00Z'),
  },
  {
    name: '"The Pragmatic Programmer" by David Thomas & Andrew Hunt',
    description: 'Oferece conselhos práticos e filosofias sobre como se tornar um desenvolvedor mais eficaz e produtivo.',
    link: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:50:00Z'),
  },
  {
    name: '"Designing Data-Intensive Applications" by Martin Kleppmann',
    description: 'Essencial para arquitetos de software e engenheiros de dados, cobre os princípios por trás da construção de sistemas de dados escaláveis e resilientes.',
    link: 'https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:40:00Z'),
  },
  {
    name: 'Coursera (Specializations/Courses)',
    description: 'Plataforma de cursos online de universidades e empresas renomadas, com especializações e certificados pagos em diversas áreas de tecnologia.',
    link: 'https://www.coursera.org/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:30:00Z'),
  },
  {
    name: 'Udemy',
    description: 'Grande marketplace de cursos online com uma vasta seleção de tutoriais em vídeo sobre praticamente qualquer tecnologia ou linguagem de programação, geralmente com custo único por curso.',
    link: 'https://www.udemy.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:20:00Z'),
  },
  {
    name: 'Pluralsight',
    description: 'Plataforma de aprendizado online focada em tecnologia, com trilhas de aprendizado, avaliações e cursos sobre desenvolvimento de software, nuvem e DevOps.',
    link: 'https://www.pluralsight.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:10:00Z'),
  },
  {
    name: 'Frontend Masters',
    description: 'Oferece cursos aprofundados sobre desenvolvimento front-end com instrutores de alto nível, cobrindo JavaScript, React, Vue, Node.js e mais.',
    link: 'https://frontendmasters.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T09:00:00Z'),
  },
  {
    name: 'Manning Publications (Books & LiveBooks)',
    description: 'Editora de livros técnicos de alta qualidade sobre programação, machine learning e sistemas, com opções de e-books e acesso online.',
    link: 'https://www.manning.com/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:50:00Z'),
  },
  {
    name: 'Educative.io',
    description: 'Plataforma interativa baseada em texto para aprendizado de programação, com cursos práticos e desafios de codificação.',
    link: 'https://www.educative.io/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:40:00Z'),
  },
  {
    name: '"Grokking Algorithms" by Aditya Bhargava',
    description: 'Um guia visual e intuitivo para entender algoritmos e estruturas de dados essenciais.',
    link: 'https://www.manning.com/books/grokking-algorithms',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:30:00Z'),
  },
  {
    name: '"Building Microservices" by Sam Newman',
    description: 'Um guia prático para projetar e construir arquiteturas baseadas em microsserviços.',
    link: 'https://www.oreilly.com/library/view/building-microservices/9781491950340/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:20:00Z'),
  },
  {
    name: 'Refactoring.Guru',
    description: 'Recurso online pago que explica padrões de refatoração, design patterns e princípios SOLID de forma visual e fácil de entender.',
    link: 'https://refactoring.guru/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:10:00Z'),
  },
  {
    name: 'Wes Bos Courses',
    description: 'Cursos populares e bem produzidos sobre JavaScript, React, CSS Grid, Flexbox e outras tecnologias web.',
    link: 'https://wesbos.com/courses/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T08:00:00Z'),
  },
  {
    name: 'Egghead.io',
    description: 'Oferece lições de vídeo concisas e focadas para desenvolvedores web, com foco em frameworks JavaScript e ferramentas modernas.',
    link: 'https://egghead.io/',
    category: 'Books & Courses',
    pricing: 'Paid',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:50:00Z'),
  },
  {
    name: 'freeCodeCamp',
    description: 'Oferece milhares de horas de conteúdo de programação interativo e certificações gratuitas em desenvolvimento web, ciência de dados e mais.',
    link: 'https://www.freecodecamp.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:40:00Z'),
  },
  {
    name: 'edX (Audit Track)',
    description: 'Permite auditar cursos de universidades de renome gratuitamente, sem acesso a certificados ou avaliações graduadas.',
    link: 'https://www.edx.org/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:30:00Z'),
  },
  {
    name: 'Codecademy (Basic Plan)',
    description: 'Oferece lições interativas gratuitas para aprender conceitos básicos de programação em várias linguagens.',
    link: 'https://www.codecademy.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:20:00Z'),
  },
  {
    name: 'Coursera (Audit Track)',
    description: 'Assim como o edX, permite auditar muitos cursos gratuitamente.',
    link: 'https://www.coursera.org/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:10:00Z'),
  },
  {
    name: 'Udemy (Free Courses Filter)',
    description: 'Possui uma seção de cursos totalmente gratuitos, geralmente introdutórios ou promocionais.',
    link: 'https://www.udemy.com/courses/free/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T07:00:00Z'),
  },
  {
    name: 'Google AI for Developers',
    description: 'Cursos e recursos gratuitos do Google para aprender sobre Machine Learning, TensorFlow e IA.',
    link: 'https://developers.google.com/machine-learning/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:50:00Z'),
  },
  {
    name: 'Microsoft Learn',
    description: 'Oferece módulos de aprendizado e caminhos de aprendizado gratuitos sobre tecnologias Microsoft, incluindo Azure, .NET, e desenvolvimento de IA.',
    link: 'https://learn.microsoft.com/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:40:00Z'),
  },
  {
    name: 'MIT OpenCourseware',
    description: 'Materiais de curso de nível universitário do MIT disponíveis gratuitamente online, incluindo cursos de ciência da computação.',
    link: 'https://ocw.mit.edu/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:30:00Z'),
  },
  {
    name: 'W3Schools',
    description: 'Um recurso web completo para aprender linguagens de programação web (HTML, CSS, JavaScript, SQL, Python, etc.) com tutoriais e exemplos.',
    link: 'https://www.w3schools.com/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:20:00Z'),
  },
  {
    name: 'The Odin Project',
    description: 'Um currículo open source de desenvolvimento web full-stack, com foco em Ruby on Rails ou JavaScript/React, que guia o aluno por projetos práticos.',
    link: 'https://www.theodinproject.com/',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:10:00Z'),
  },
  {
    name: 'Exercism',
    description: 'Plataforma que oferece desafios de programação em dezenas de linguagens, com mentoring gratuito por voluntários.',
    link: 'https://exercism.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T06:00:00Z'),
  },
  {
    name: 'Hack The Box (Free Tier)',
    description: 'Plataforma de cibersegurança que oferece laboratórios práticos para aprender e aprimorar habilidades de ethical hacking (máquinas gratuitas para uso).',
    link: 'https://www.hackthebox.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:50:00Z'),
  },
  {
    name: '"You Don\'t Know JS Yet" (Book Series) by Kyle Simpson',
    description: 'Uma série de livros open source no GitHub que aprofunda no JavaScript, cobrindo tópicos avançados.',
    link: 'https://github.com/getify/You-Dont-Know-JS',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:40:00Z'),
  },
  {
    name: 'Google\'s Python Class',
    description: 'Um curso gratuito do Google para pessoas com pouca experiência em programação, focando em Python.',
    link: 'https://developers.google.com/edu/python/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:30:00Z'),
  },
  {
    name: 'Learn Git Branching',
    description: 'Um tutorial interativo e visual para aprender Git Branching, essencial para controle de versão.',
    link: 'https://learngitbranching.js.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:20:00Z'),
  },
  {
    name: 'Open Source Society University (OSSU)',
    description: 'Um currículo curado de cursos online gratuitos para uma educação de ciência da computação de nível universitário.',
    link: 'https://github.com/ossu/computer-science',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:10:00Z'),
  },
  {
    name: 'HackerRank (Community Challenges)',
    description: 'Plataforma com desafios de programação e algoritmos para praticar e aprimorar habilidades, com muitos problemas e cursos gratuitos.',
    link: 'https://www.hackerrank.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T05:00:00Z'),
  },
  {
    name: 'LeetCode (Free Problems)',
    description: 'Plataforma popular para praticar problemas de algoritmos e estruturas de dados, essencial para entrevistas de emprego em tecnologia (muitos problemas são gratuitos).',
    link: 'https://leetcode.com/',
    category: 'Books & Courses',
    pricing: 'Free Tier',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:50:00Z'),
  },
  {
    name: 'The Missing Semester of Your CS Education (MIT)',
    description: 'Um curso curto e gratuito do MIT focado em ferramentas e habilidades práticas que não são ensinadas nos currículos tradicionais de CS.',
    link: 'https://missing.csail.mit.edu/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:40:00Z'),
  },
  {
    name: 'Roadmap.sh',
    description: 'Coleções de roadmaps de aprendizado para desenvolvedores, cobrindo diferentes especializações (frontend, backend, DevOps, etc.), de código aberto.',
    link: 'https://roadmap.sh/',
    category: 'Books & Courses',
    pricing: 'Open Source',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:30:00Z'),
  },
  {
    name: 'MDN Web Docs (Mozilla)',
    description: 'Documentação abrangente e tutoriais sobre tecnologias web (HTML, CSS, JavaScript, APIs Web), um recurso essencial e gratuito para desenvolvedores.',
    link: 'https://developer.mozilla.org/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:20:00Z'),
  },
  {
    name: 'dev.to',
    description: 'Uma comunidade de desenvolvedores onde eles compartilham artigos e tutoriais sobre diversas tecnologias, muitos deles guias passo a passo.',
    link: 'https://dev.to/',
    category: 'Books & Courses',
    pricing: 'Free',
    icon: 'BookOpen',
    createdAt: new Date('2024-05-18T04:10:00Z'),
  },
  
  // UI & Design
  {
    name: 'Figma (Professional/Organization Plans)',
    description: 'Uma plataforma de design colaborativa para criar interfaces de usuário, protótipos e sistemas de design. Os planos pagos oferecem recursos avançados para equipes.',
    link: 'https://www.figma.com/pricing/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T10:00:00Z'),
  },
  {
    name: 'Sketch',
    description: 'Um editor de gráficos vetoriais exclusivo para macOS, amplamente utilizado para design de UI/UX, com um modelo de licença paga.',
    link: 'https://www.sketch.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:50:00Z'),
  },
  {
    name: 'Adobe XD',
    description: 'Uma ferramenta de design de experiência do usuário para projetar e prototipar interfaces de usuário para aplicativos e web, parte da Creative Cloud.',
    link: 'https://www.adobe.com/products/xd.html',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:40:00Z'),
  },
  {
    name: 'InVision',
    description: 'Plataforma para prototipagem interativa, fluxo de trabalho de design e colaboração, com planos pagos para equipes maiores e funcionalidades avançadas.',
    link: 'https://www.invisionapp.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:30:00Z'),
  },
  {
    name: 'Principle (macOS)',
    description: 'Uma ferramenta de design de animação e prototipagem interativa para interfaces de usuário, simples e poderosa.',
    link: 'https://principleformac.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:20:00Z'),
  },
  {
    name: 'Axure RP',
    description: 'Uma ferramenta robusta para wireframing, prototipagem e especificação, focada em designs complexos e interativos.',
    link: 'https://www.axure.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:10:00Z'),
  },
  {
    name: 'Zeplin',
    description: 'Uma ferramenta de colaboração que conecta designers e desenvolvedores, exportando designs e fornecendo especificações, assets e trechos de código.',
    link: 'https://zeplin.io/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T09:00:00Z'),
  },
  {
    name: 'UXPin',
    description: 'Plataforma de design de produto de ponta a ponta que permite projetar, prototipar e documentar experiências de usuário.',
    link: 'https://www.uxpin.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:50:00Z'),
  },
  {
    name: 'Affinity Designer',
    description: 'Um editor de gráficos vetoriais e raster alternativo ao Adobe Illustrator, conhecido por seu desempenho e preço único.',
    link: 'https://affinity.serif.com/en-us/designer/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:40:00Z'),
  },
  {
    name: 'Flinto (macOS)',
    description: 'Uma ferramenta para criar protótipos interativos e micro-interações para iOS, Android e web.',
    link: 'https://www.flinto.com/',
    category: 'UI & Design',
    pricing: 'Paid',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:30:00Z'),
  },
  {
    name: 'Figma (Starter Plan)',
    description: 'Oferece um plano gratuito para uso individual com recursos essenciais de design e prototipagem.',
    link: 'https://www.figma.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:20:00Z'),
  },
  {
    name: 'Canva (Free Plan)',
    description: 'Uma ferramenta de design gráfico online para criar uma variedade de materiais visuais, incluindo gráficos para redes sociais e apresentações, com muitos templates gratuitos.',
    link: 'https://www.canva.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:10:00Z'),
  },
  {
    name: 'Miro (Free Plan)',
    description: 'Um quadro branco online colaborativo para brainstorming, diagramação, planejamento e workshops de design thinking. O plano gratuito é limitado.',
    link: 'https://miro.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T08:00:00Z'),
  },
  {
    name: 'Whimsical',
    description: 'Combina wireframes, fluxogramas, notas adesivas e documentos em uma ferramenta de colaboração visual rápida. Oferece um plano gratuito limitado.',
    link: 'https://whimsical.com/pricing',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:50:00Z'),
  },
  {
    name: 'Marvel',
    description: 'Uma plataforma de prototipagem e colaboração de design que permite transformar mockups em protótipos interativos. Tem um plano gratuito para um projeto.',
    link: 'https://marvelapp.com/pricing/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:40:00Z'),
  },
  {
    name: 'Font Awesome (Free Icons)',
    description: 'Uma biblioteca popular de ícones escaláveis baseados em vetor que podem ser personalizados com CSS. A versão gratuita tem muitos ícones.',
    link: 'https://fontawesome.com/',
    category: 'UI & Design',
    pricing: 'Free Tier',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:30:00Z'),
  },
  {
    name: 'Google Fonts',
    description: 'Uma vasta biblioteca de fontes gratuitas e de código aberto otimizadas para web, que podem ser usadas livremente em qualquer projeto.',
    link: 'https://fonts.google.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:20:00Z'),
  },
  {
    name: 'GIMP (GNU Image Manipulation Program)',
    description: 'Um editor de imagens de código aberto poderoso, uma alternativa gratuita ao Photoshop, para manipulação de fotos, composição de imagens e criação de arte.',
    link: 'https://www.gimp.org/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:10:00Z'),
  },
  {
    name: 'Inkscape',
    description: 'Um editor de gráficos vetoriais de código aberto, ideal para criar ilustrações, diagramas, arte de linha, gráficos web e muito mais.',
    link: 'https://inkscape.org/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T07:00:00Z'),
  },
  {
    name: 'Blender',
    description: 'Software de modelagem 3D, animação, renderização, composição, rastreamento de movimento, edição de vídeo e pipeline de animação 2D, tudo de código aberto.',
    link: 'https://www.blender.org/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:50:00Z'),
  },
  {
    name: 'Penpot',
    description: 'Uma plataforma de prototipagem e design de código aberto, baseada na web, concorrente do Figma.',
    link: 'https://penpot.app/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:40:00Z'),
  },
  {
    name: 'UI Libraries & Component Frameworks',
    description: 'Bibliotecas de componentes de UI de código aberto que fornecem blocos de construção prontos para uso para interfaces web (ex: Material-UI, Ant Design, Bootstrap).',
    link: 'https://mui.com/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:30:00Z'),
  },
  {
    name: 'Unsplash',
    description: 'Um vasto banco de dados de fotos de alta resolução gratuitas para uso em projetos de design.',
    link: 'https://unsplash.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:20:00Z'),
  },
  {
    name: 'Pexels',
    description: 'Semelhante ao Unsplash, oferece fotos e vídeos de estoque de alta qualidade, gratuitos para uso.',
    link: 'https://www.pexels.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:10:00Z'),
  },
  {
    name: 'Open Peeps',
    description: 'Uma biblioteca de ilustrações desenhadas à mão de pessoas, combináveis para criar diversas poses e cenários. Gratuito para uso pessoal e comercial.',
    link: 'https://www.openpeeps.com/',
    category: 'UI & Design',
    pricing: 'Free',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T06:00:00Z'),
  },
  {
    name: 'Lucide Icons',
    description: 'Uma biblioteca de ícones de código aberto, limpos, personalizáveis e consistentes, ideal para interfaces de usuário.',
    link: 'https://lucide.dev/',
    category: 'UI & Design',
    pricing: 'Open Source',
    icon: 'Palette',
    createdAt: new Date('2024-05-17T05:50:00Z'),
  },
];

export async function getResources(): Promise<Resource[]> {
  if (!db) {
    console.warn("Firestore is not initialized. Returning sample resources.");
    // Sort local data by date before returning
    return sampleResources
      .map((r, i) => ({ ...r, id: `local-${i}`})) // Add a temporary local id
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  try {
    const resourcesCollection = collection(db, 'resources');
    const q = query(resourcesCollection, orderBy('createdAt', 'desc'));
    const querySnapshot = await getDocs(q);
    
    if (querySnapshot.empty) {
        console.log("No resources found in Firestore, populating with sample data.");
        const batch = (await import('firebase/firestore')).writeBatch(db);
        sampleResources.forEach(resource => {
            const docRef = doc(collection(db, 'resources')); // Firestore will generate ID
            batch.set(docRef, { ...resource, createdAt: Timestamp.fromDate(resource.createdAt) });
        });
        await batch.commit();
        
        // After populating, fetch again to get correct IDs and sorted data
        const newSnapshot = await getDocs(q);
        return newSnapshot.docs.map(doc => {
            const data = doc.data();
            return {
                id: doc.id,
                ...data,
                createdAt: (data.createdAt as Timestamp).toDate(),
            } as Resource;
        });
    }
    
    return querySnapshot.docs.map(doc => {
      const data = doc.data();
      return {
        id: doc.id,
        ...data,
        createdAt: (data.createdAt as Timestamp).toDate(),
      } as Resource;
    });
  } catch (error) {
    console.error("Error fetching resources:", error);
    // Fallback to local sample data on error
    return sampleResources
      .map((r, i) => ({ ...r, id: `local-${i}`}))
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }
}

export async function getResourceById(id: string): Promise<Resource | null> {
    if (!db) {
        console.warn("Firestore is not initialized.");
        // Find by the custom 'id' field in the local sample data, although it's not present anymore.
        // This will likely not work for local data, but is fine as it's a fallback.
        const localResource = sampleResources.find((r: any) => r.id === id);
        return localResource ? { ...localResource, id } as Resource : null;
    }

    try {
        const resourceRef = doc(db, 'resources', id);
        const docSnap = await getDoc(resourceRef);

        if (!docSnap.exists()) {
            return null;
        }

        const data = docSnap.data();
        return {
            id: docSnap.id,
            ...data,
            createdAt: (data.createdAt as Timestamp).toDate(),
        } as Resource;

    } catch (error) {
        console.error("Error fetching resource by id:", error);
        return null;
    }
}

export async function addResource(resourceData: Omit<Resource, 'id' | 'createdAt'>) {
    if (!db) throw new Error("Firestore is not initialized.");

    const newResource = {
        ...resourceData,
        createdAt: serverTimestamp(),
    };
    
    await addDoc(collection(db, 'resources'), newResource);
    revalidatePath('/dashboard/resources');
    revalidatePath('/resources');
}

export async function updateResource(id: string, resourceData: Partial<Omit<Resource, 'id' | 'createdAt'>>) {
    if (!db) throw new Error("Firestore is not initialized.");
    
    const resourceRef = doc(db, 'resources', id);
    await updateDoc(resourceRef, resourceData);

    revalidatePath('/dashboard/resources');
    revalidatePath('/resources');
}

export async function deleteResource(id: string) {
    if (!db) throw new Error("Firestore is not initialized.");
    
    const resourceRef = doc(db, 'resources', id);
    await deleteDoc(resourceRef);

    revalidatePath('/dashboard/resources');
    revalidatePath('/resources');
}
