# Workflow to build and deploy the Next.js app to Firebase App Hosting
name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

# These permissions are required for authentication with Google Cloud
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # The 'firebase-apphosting-deploy' action handles all the necessary steps:
      # - Sets up Node.js
      # - Installs dependencies
      # - Builds the app
      # - Deploys to Firebase App Hosting
      - name: Deploy to Firebase App Hosting
        uses: firebase/firebase-apphosting-deploy@v0.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
